### ISSUE TITLE
App installs, but watch face unavailable

### ISSUE THREAD

**Issue by jasonsalas** [btrax/sample-watch-face-official-api#3]
Hello!

I've cloned the repo, built the mobile app as a release, and sideloaded it onto my phone via ADB, and see that the wearable app installed automatically on my watch, but it's not showing up as an available watch face in the Android Wear app. Is there a line in the code that's missing that makes it selectable in the mobile app and in the watch face picker on the watch?

Thanks!

**Comment by jasonsalas** [comment]
Oops...my mistake...I didn't capitalize a manifest entry like I should have. It works. :)

**Comment by yshiga** [comment]
Oh good!
